domain: "localhost:8000"
base_url: "http://localhost:8000"
db: "postgres://watgok:watgok555@128.199.135.75/watgok_db?sslmode=require"
session_host: "localhost:6379"
session_prefix: "sess_watgok:"
session_key: "sess_watgok_dwppw"
session_secret: "sess_watgoksalsplfplwpql112"
fb_token: "fdab9aa1c7caea71156a4085826bd76c"
bucket_name: "watgok_bucket"