domain: "localhost:8080"
base_url: "http://localhost:8080"
db: "postgres://masterdev:111222333444555@127.0.0.1/mydb?sslmode=require"
session_host: "localhost:6379"
session_prefix: "sess_master:"
session_key: "keqvbftozwww{:lsd:]{}ldp@gdads"
fb_token: "fdab9aa1c7caea71156a4085826bd76c"